### ISSUE TITLE
snabbdom subtree render

### ISSUE THREAD

**Issue by marcusnielsen** [AlexGalays/kaiju#3]
Hi,

I've seen many discussions now about rendering subtrees in snabbdom, and the best lead seems to be kaiju's source code. Is the patching code something that we could extract somehow so it's available to all snabbdom users? I might even be on the wrong track since I'm not that sure of what and how kaiju makes the patching of subtree vNodes. Could you help shed some light for us?

**Comment by AlexGalays** [comment]
Sorry for replying sooo late.

I don't think the patching code could be reused in its current form, but maybe it could help someone writing a similar system.

subtree rendering works in kaiju by using a tree of components. Each component can have props and states, and they only get their `render` function reevaluated if at least one of props or state changed. render is called from within a requestAnimationFrame call. Each component can get rendered indivividually, without its parent rendering, if only its state changed. state is wired in the `connect` method and can pull from any any outside source.

**Comment by marcusnielsen** [comment]
Sounds like the setup I do with `React` and `most.js`. And no worries for the late reply, it's awesome that you actually did reply!

I will try to look at the source code and see if I can get it.

**Comment by AlexGalays** [comment]
Yes, react already had an advantage to do that kind of thing: setState :)
