### ISSUE TITLE
Fullpage application problem

### ISSUE THREAD

**Issue by katyo** [AlexGalays/kaiju#4]
I used snabbdom at the moment to build application which able to attach to `document.documentElement`. Also this app compatible with server-side rendering. So it renders root page tree starting from `html` node. Snabbdom works fine for this case, but I failed to start application using kaiju. The problem of kaiju in that by default it append child to node and don't provide any ways to attach to node itself.

**Comment by AlexGalays** [comment]
Hello,

I think I know what you mean, but can you post your `startApp` call to be sure?

**Comment by katyo** [comment]
I pushed my code to repository:
https://github.com/katyo/kaiju-fullpage

Clone it and run: `npm install; npm run compile`

**Comment by katyo** [comment]
Hmm...
As I can see the root node cannot be a stateful component in current implementation.
It's not so good for me.

**Comment by AlexGalays** [comment]
That should be easy to fix, there's no good reason why the root can't be a component :)

**Comment by katyo** [comment]
Can we avoid creating `component` nodes at all? For example, the snabbdom `thunk` no need any wrapper.

**Comment by AlexGalays** [comment]
Actually, I just tried; you can use a component for the root; just have to invoke it first :)

e.g
`startApp({ app:  mycomponent() })`

**Comment by katyo** [comment]
Unfortunately it wouldn't work because the component is wrapped by the `component` element.

**Comment by AlexGalays** [comment]
Ok!

As far as I understand, you have two issues:

1) A component cannot be used as the root in your case as it introduces an extra layer
A workaround should be doable. Do you need the top level component to be an actual `component`? i.e you could just have a function that returns h('html') and the `body` section could then be made of components.

2) startApp() assumes people will want their app to be added to whatever container is passed, not fully replace it.
What do you think about adding a mode where it has snabbdom patch's default behavior (full replace)? I'm generally not a fan of function switches, but there might be a use case there.
Something like  `replaceElm`.

**Comment by katyo** [comment]
Yes of course.

I would like to offer the next workflow for `startApp`:

1. Constructing patch function (i.e. snabbdom's `init`).
2. Reading existing DOM from `elm` to `VNode` tree (for example using snabbdom's `toVNode`).
3. Doing initial synchronous render (i.e. snabbdom's `patch`) using readed initial `VNode` tree.

**Comment by AlexGalays** [comment]
Hello,

Sorry for the delay. Can you try `0.22.4`?

- Use `replaceElm`: true in `startApp`
- Optionally if you want to use a component as the root, you can do the following:

```ts
function app() {
  const comp = Component<Props, State>({ name: 'app', sel: 'html', props, initState, connect, render })
  comp.key = undefined
  return comp
}
```

as components always have a key so we can differentiate between components of a different kind when patching, but in your case, you need the client side component to simply consider the existing html node to be the initial component render output, and just reuse that.
