### ISSUE TITLE
snabbdom modules parameter in startApp is redundant

### ISSUE THREAD

**Issue by ludmiloff** [AlexGalays/kaiju#9]
Snabbdom modules parameter when calling startApp is redundant, why not require all the modules and pass them to the snabbdom init instead.

**Comment by AlexGalays** [comment]
Hello,

I used to do that but the whole point of snabbdom modules is that they are opt-in (each module contribute a bit to the diffing runtime cost and you might not use every capabilities on every single project, for instance inline styles) and you may want to load any number of custom extras modules, some of which may fully replace the snabbdom "official" equivalent.

**Comment by ludmiloff** [comment]
You might be correct, then what about implementing the parameter as optional and if present, then obey the passed value, if not - create default set of modules.
Sorry I'm writing to closed issue
